name: Build and deploy container app to Azure Web App - mywebsitelr

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-website:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://mywebsite.azurecr.io/
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: mywebsite.azurecr.io/${{ secrets.REGISTRY_USERNAME }}/personalwebsite/latest:latest
        context: ./personal_website

  build-auth:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://mywebsite.azurecr.io/
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: mywebsite.azurecr.io/${{ secrets.REGISTRY_USERNAME }}/authorisation:latest
        context: ./authorisation