version: '3'

networks:
  serv:
    name: serv
  

services:  

  auth_db:
    image: postgres
    container_name: auth_db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=auth_db

  authorisation:
    image: mywebsite.azurecr.io/mywebsite/authorisation:latest
    restart: always
    depends_on:
      - auth_db
    environment:
      - POSTGRES_URL=auth_db:5432
    ports:
      - 9000:9000

  
  website:
    image: mywebsite.azurecr.io/mywebsite/personalwebsite/latest:latest
    restart: always

    ports:
      - 80:80
      - 443:443

