on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy-website:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Azure authentication
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
#     - name: Azure CLI script to provision a new Web App for Container
#       uses: azure/CLI@v0-beta
#       with:
#         azcliversion: latest
#         inlineScript: |
#           az webapp create --resource-group ${{ env.AZURE_RESOURCE_GROUP }} --plan ${{ env.AZURE_APP_PLAN }} --name ${{ env.AZURE_WEBAPP_NAME }}  -i nginx
    - name: ACR authentication
      uses: azure/docker-login@v1
      with:
        login-server: mywebsite.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    - name: Docker Build & Push to ACR
      run: |
        docker build personal_website/ -t mywebsite.azurecr.io/nodejsapp:${{ github.sha }}
        docker push mywebsite.azurecr.io/nodejsapp:${{ github.sha }}